---
kind: pipeline
type: kubernetes
name: default
steps:
# TODO: move this to a central location, may be drone bootstrap.
# - name: run
#   image: docker
#   volumes:
#   - name: dockersock
#     path: /var/run/docker.sock
#   commands:
#   - docker run --privileged --rm tonistiigi/binfmt --install all
- name: dockerx
  image: thegeeklab/drone-docker-buildx:20.10.14
  privileged: true
  settings:
    experimental: true
    auto_tag: true
    platforms: 
    - linux/arm/v7
    username: rajiteh
    password:
      from_secret: gitlab_token
    repo: registry.gitlab.com/rajiteh/orca_containers
    registry: registry.gitlab.com
    auto_tag_suffix: led-hack
# - &kubeconfig_step
#   name: helm-deploy
#   image: alpine/helm:3.8.0
#   secrets: [orca_k3s_kubeconfig_b64]
#   environment: 
#     KUBECONFIG: /tmp/kubeconfig.yaml
#     ORCA_K3S_KUBECONFIG_B64:
#       from_secret: orca_k3s_kubeconfig_b64
#   commands:
#     - &setup_kubeconfig_command echo "$${ORCA_K3S_KUBECONFIG_B64}" | base64 -d > $${KUBECONFIG}
#     - helm upgrade led-hack --install --create-namespace --namespace ls90-led-hack --debug chart/led-hack
# - <<: *kubeconfig_step
#   name: deployment-rollout
#   image: bitnami/kubectl:1.22.7
#   commands:
#     - *setup_kubeconfig_command
#     - kubectl rollout restart --namespace ls90-led-hack deployment led-hack